# Generated by Django 3.0.5 on 2020-04-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
