# Generated by Django 3.0.5 on 2020-04-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_event_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(default='website/default.jpg', upload_to='website'),
        ),
    ]
