# Generated by Django 3.0.5 on 2020-04-15 22:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200414_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500),
        ),
    ]
