# Generated by Django 3.0.5 on 2020-04-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_join'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Join',
            new_name='JoinEvent',
        ),
    ]
