# Generated by Django 3.0.5 on 2020-04-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_joinevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('leader', models.CharField(max_length=50)),
                ('img', models.ImageField(default='website/default.jpg', upload_to='website/ministry')),
            ],
        ),
    ]
