# Generated by Django 3.0.5 on 2020-04-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_ministry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(default='website/default.jpg', upload_to='website/events'),
        ),
    ]
