# Generated by Django 3.0.5 on 2020-04-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200417_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('pastor', models.CharField(max_length=50)),
                ('video_link', models.URLField(max_length=400)),
                ('video_thumbnail', models.ImageField(default='website/default.jpg', upload_to='website/sermon')),
            ],
        ),
    ]
