# Generated by Django 3.0.5 on 2020-04-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_sermons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sermons',
            new_name='Sermon',
        ),
    ]
