# Generated by Django 3.0.5 on 2020-04-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20200419_0119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sermon',
            new_name='Service',
        ),
    ]
