# Generated by Django 3.0.5 on 2020-04-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20200419_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinevent',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
