# Generated by Django 3.0.5 on 2020-04-23 01:17

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200423_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joinevent',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=10),
        ),
    ]
